//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Worser.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lkQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lkQuestion()
        {
            this.lkQuestion1 = new HashSet<lkQuestion>();
            this.lkQuestions = new HashSet<lkQuestion>();
        }
    
        public int id { get; set; }
        public string question { get; set; }
        public int rank { get; set; }
        public Nullable<System.DateTime> activeEndDate { get; set; }
        public int isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lkQuestion> lkQuestion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lkQuestion> lkQuestions { get; set; }
    }
}
